language: erlang
otp_release:
   - 19.3
   - 20.3
   - 21.3
   - 22.0.2
   - 23.0
script:
    - wget https://github.com/erlang/rebar3/releases/download/3.11.1/rebar3 && chmod +x rebar3 && ./rebar3 update
    - ./rebar3 do compile, ct
